name: Pull Request Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
env:
  BASE_REF: ${{ github.event.pull_request.base.sha }}

jobs:
  Changelog-Check:
    name: Changelog Mention
    # If the No Documentation Needed label is set, then workflow will not be executed
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'No Documentation Needed') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check that Changelog has been updated
        run: |
          # Check that Changelog has been updated
          if ! git diff --quiet $(git merge-base $BASE_REF HEAD) -- "整合包说明/更新改动说明.md";
          then
            echo "感谢您记得更新变更日志！😋"
            exit 0
          else
            echo "你好像忘了更新变更日志！🧐"
            echo "请在“整合包说明/更新改动说明”中提及您的更改。"
            exit 1
          fi

  Documentation-Check:
    name: Documentation for Changes
    # If the No Documentation Needed or Bugfix label is set, then workflow will not be executed
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'No Documentation Needed') && !contains(github.event.pull_request.labels.*.name, 'Bugfix') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check that Documentation has been updated
        run: |
          # Check that Documentation has been updated
          if ! git diff --quiet $(git merge-base $BASE_REF HEAD) -- "整合包说明/额外功能说明.md";
          then
            echo "感谢您记得更新功能说明！😋"
            exit 0
          else
            echo "你好像忘了更新功能说明！🧐"
            echo "请在“整合包说明/额外功能说明”中提及您的更改。"
            exit 1
          fi
